### ISSUE TITLE
image directory

### ISSUE THREAD

**Issue by cngonzalez** [learn-co-curriculum/learn-deploy-on-day-one#16]
There's a mention here of uploading photos to an image directory, although the lesson itself suggests students upload photos to imgur (which makes things a little confusing!)

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the _content_ of this lesson. If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by aturkewi** [comment]
@bhollan or @ivalentine
Can one of you put in a PR to fix this issue when you are next have time to go through some deploy-on-day-ones?

**Comment by bhollan** [comment]
@aturkewi Is there something else you want other than the changes in #17 ?

**Comment by aturkewi** [comment]
Nope! That was it. Thanks for pointing that out @bhollan

**Comment by aturkewi** [comment]
Nope! That was it. Thanks for pointing that out @bhollan
