### ISSUE TITLE
students.learn.co no longer exists

### ISSUE THREAD

**Issue by ktravers** [learn-co-curriculum/learn-deploy-on-day-one#20]
domain doesn't seem to exist. here's what i get when i try to navigate to the link in the readme on my home network:

<img width="1280" alt="screen shot 2018-06-17 at 7 47 58 pm" src="https://user-images.githubusercontent.com/8152930/41513290-89083822-7267-11e8-9f74-ecb721adc450.png">

**Comment by Atsoamazed** [comment]
This lesson needs to be updated
