### ISSUE TITLE
The deployment section should be yanked

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/learn-deploy-on-day-one#5]
I think having them publish their forks themselves by editing the CNAME is a bad idea and has already created issues for everyone trying to solve this lab.

cc @jmburges @AnnJohn

**Comment by jmburges** [comment]
hey @aviflombaum, can you point to where the CNAME stuff is causing issues?

I really wanted the students to actually get to deploy without having to wait for us to merge the PR! It should be pretty straight forward. Just delete the CNAME file and push.
