### ISSUE TITLE
We cannot have them edit style.css

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/learn-deploy-on-day-one#6]
If you look at a diff:

https://github.com/learn-co-students/learn-deploy-on-day-one-v-000/pull/4/files#diff-fe4aeb7ba4bfe5050b46d913b61e60aeL222

They can't edit that line - everyone is editing the same background. We need to make it so they add their own stylesheet and link to it on just their profile page so taht people aren't overwriting the same style in the same file...

cc @jmburges @AnnJohn

**Comment by aviflombaum** [comment]
I like the way he did it with IDs

https://github.com/learn-co-students/learn-deploy-on-day-one-v-000/pull/2/files#diff-fe4aeb7ba4bfe5050b46d913b61e60aeL167

but I'd still rather have them all add their own person.name.css and link to it on just their profile page. Makes them add a `<link>` tag which is cool.

**Comment by jmburges** [comment]
So IDs was the intended way. Similar to how I had Matt and Diane beta-test it like this https://github.com/learn-co-curriculum/learn-deploy-on-day-one/pull/2/files 

I wanted them to have to do a bit of sleuthing and pattern matching to figure it out, but looks like I should have removed the profile.html. I'm of two minds...I kinda want to respond and be like hey! take a look at how everyone else did it. Can you match theirs? And explain why the ID method is better. 

We should explain to him that, and also for ease of cloning in the future make it be required that they create separate files.
